In [1]:
# import numpy as np
import numpy as np

In [3]:
# print numpy verison and conf
print(np.__version__)
print(np.show_config())

2.2.6
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30159",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.0",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30159",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.29",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-gnu2g9dg/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib d

c:\Users\123as\OneDrive\Desktop\codeFolder\pythonFolder\numpyExercise\.venv\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [6]:
# create null vector of size 10

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# how to find the memory size of any array

arr = np.random.randint(20, 30, size=(2, 2, 2))
arr.itemsize * arr.size

4

In [ ]:
# get the documentation of the numpy add function from command line
np.info(np.add) # or np.add.__doc__
# if you want to use command line only: !python -c "import numpy as np; np.info(np.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [24]:
# create a null verctor of size 10 but the fifth value which is 1

arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
# create a vector with random values between 10 to 49
arr = np.random.randint(10, 49, (10,))
arr
# create a vector with values ranging from 10 to 49
arr = np.arange(10, 49)
arr


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [30]:
# reverse a vector (first element becomes last)

arr = arr[::-1]
arr 

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [ ]:
# create a 3x3 matrix with values ranging from 0 to 8

arr = np.arange(0, 9)
arr = arr.reshape((3, 3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# find indices of non-zero elements from [1, 2, 0, 0, 4, 0]

arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.where(arr != 0)
indices

# easier solution: indices = np.nonzero(arr)

(array([0, 1, 4]),)

In [ ]:
# create a 3x3 identity matrix

arr = np.identity(3)
arr

# another solution
# np.eye(N = 3, M = 4, k = 1, dtype = int);  here; N is rows, M is columns (N by default), k is the position (1 up from the main diagonal)
arr = np.eye(3)
arr


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
# create 3x3x3 array with random values

arr = np.random.random((3, 3, 3))
arr

array([[[0.87076762, 0.11774753, 0.88042345],
        [0.64170295, 0.74566082, 0.96730697],
        [0.89211589, 0.61239515, 0.36194375]],

       [[0.01380846, 0.49844208, 0.39517705],
        [0.97806491, 0.28629727, 0.84327917],
        [0.81595518, 0.16472598, 0.51869395]],

       [[0.55330029, 0.4586636 , 0.81932172],
        [0.1618772 , 0.56105832, 0.38586712],
        [0.32089225, 0.16110237, 0.40871765]]])

In [56]:
# create a 10x10 array with random values and find the minimum and maximum values
arr = np.random.random((10, 10))
print("minimum: ", arr.min())
print("maximum: ", arr.max())
arr

minimum:  0.0010588511225764208
maximum:  0.9735766774505509


array([[0.20763069, 0.61245048, 0.200232  , 0.77628628, 0.39213284,
        0.65404576, 0.70181292, 0.55185092, 0.26771121, 0.46024863],
       [0.34118829, 0.45676497, 0.10189232, 0.68253944, 0.41095276,
        0.25074218, 0.92312475, 0.77307181, 0.33946613, 0.02463195],
       [0.13623496, 0.59192858, 0.85970285, 0.5973431 , 0.08544107,
        0.80947162, 0.37214308, 0.83416753, 0.0882261 , 0.90576061],
       [0.38394784, 0.57017033, 0.03395913, 0.73583486, 0.75210952,
        0.7097867 , 0.50147738, 0.02477195, 0.06736805, 0.07858767],
       [0.91286518, 0.34957191, 0.13816325, 0.27193223, 0.82680681,
        0.28627585, 0.54520383, 0.69627544, 0.94894259, 0.33044734],
       [0.49373486, 0.40382785, 0.5694313 , 0.57705183, 0.85472766,
        0.88437654, 0.72112864, 0.33513806, 0.63088606, 0.54138864],
       [0.90610706, 0.08504438, 0.96435564, 0.89231696, 0.0576312 ,
        0.63857807, 0.58352118, 0.93128085, 0.73934072, 0.26274918],
       [0.20789497, 0.97357668, 0.5951180

In [57]:
# create a random vector of size 30 and find the mean value

arr = np.random.random((30, ))
mean = arr.mean()
mean

np.float64(0.4207103018760182)

In [68]:
# create a 2d array with 1 on the border and 0 inside

arr = np.ones((5, 5))
arr2 = np.zeros((3, 3))
arr[1:4, 1:4] = arr2 # or 0, a constant value
arr


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [78]:
# how to add a border (filled with 0's) around an existing array?
size = 5
arr1 = np.random.random((size, size))

arr2 = np.zeros((size+2, size+2))
arr2[1:size+1, 1:size+1] = arr1
arr2

# easier solution

size = 2
arr1 = np.random.random((size, size))
arr1 = np.pad(arr1, 1)
arr1



array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.20541692, 0.35185749, 0.        ],
       [0.        , 0.38306923, 0.02256379, 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [ ]:
# what is the result of the following expressions?
                            # My expectations | Answers
                            # -------------------------
0 * np.nan                  # np.nan            nan 
np.nan == np.nan            # false             False
np.inf > np.nan             # true              False
np.nan - np.nan             # np.nan            nan
np.nan in set([np.nan])     # false             True
0.3 == 3 * 0.1              # false             False

In [106]:
# create a 5x5 matrix with values 1, 2, 3, 4 just below the diagonal

size = 5

arr = np.eye(size, size, -1) 
for i in range(1, size - 1):
    arr[i: size, i: size] += np.eye(size-i, size-i, -1)

arr

# more optimized solution using ADVANCED INDEXING

matrix = np.zeros((size, size))
arr = np.arange(1, 5)

matrix[arr, arr - 1] = arr
matrix

# a better solution using NP.DIAG

arr2 = np.diag(np.arange(1, 5), -1)
arr2

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [118]:
# Create a 8x8 matrix and fill it with a checkerboard pattern
size = 8
checkboard = np.zeros((size, size))

for i in range(size):
    if i % 2 == 1:
        checkboard += np.diag(np.ones((size-i,)), i) + np.diag(np.ones((size-i,)), -i)

checkboard

# better solution

checkerboard = np.zeros((size, size))
checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1
checkerboard


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [ ]:
# Consider a (6, 7, 8) shape array, what is the index (x, y, z) of the 100th element

# my gues is: (3, 2, 2) but if I count in reverse I get: (1, 5, 3)
np.unravel_index(99, (6, 7, 8))

(np.int64(1), np.int64(5), np.int64(3))

In [128]:
# create a checkerboard 8x8 matrix using the tile function

np.tile((0, 1), (8, 4))

# another solution

np.tile(np.array([[0, 1], [1, 0]]), (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
# Normalize a 5x5 matrix

notNormal = np.random.randint(0, 10, (5, 5))
normal = (notNormal - np.mean(notNormal)) / (np.std(notNormal))
normal

array([[ 0.86166053,  0.48373924, -1.40586718,  1.6175031 , -1.02794589],
       [ 0.10581796,  1.6175031 ,  0.10581796,  1.6175031 , -0.65002461],
       [-0.65002461, -0.65002461, -1.02794589,  0.86166053,  0.48373924],
       [ 1.23958181, -0.27210332,  0.86166053, -1.02794589, -1.40586718],
       [ 0.10581796,  0.48373924, -1.40586718, -1.40586718,  0.48373924]])

In [ ]:
# Create a custom dtype that describes a color as four unsigned bytes (RGBA)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

In [ ]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

matrix1 = np.random.random((5, 3))
matrix2 = np.random.random((3, 2))

product = np.matmul(matrix1, matrix2)
product

# alternatives
product = matrix1 @ matrix2
product = np.dot(matrix1, matrix2)

array([[0.85914914, 1.29479905],
       [0.69948811, 1.06719198],
       [0.44134146, 0.88466804],
       [1.32250411, 1.46606119],
       [0.70009121, 1.03978096]])

In [ ]:
# Given a 1D array, negate all elements which are between 3 and 8, in place

arr1D = np.random.randint(0, 20, 20)
arr1D = np.where((arr1D > 3) & (arr1D < 8), -arr1D, arr1D) # you can use arr1D.__neg__() instead of -arr1D
arr1D



array([19, -7, 19,  1,  0, 15,  0, 11,  2, -6, -7, 11, 19, 10, 17, -5, 17,
       17, -7,  0], dtype=int32)

In [ ]:
# 26 What is the output of the following script?

print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

# My guess: [-1, 0, 1, 2, 3]
# Answer: 9 and 10

In [ ]:
# Consider an integer vector Z, which of these expressions are legal?

"""                     Answers
    Z**Z                legal
    2 << Z >> 2         legal
    Z <- Z              legal
    1j * Z              legal
    Z/1/1               legal
    Z<Z>Z               legal

"""

In [ ]:
# What are the result of the following expressions?

np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

In [148]:
# How to round away from zero a float array?

fltArr = np.random.random((5, 5))*100
fltArr = np.ceil(fltArr)
fltArr

array([[35., 43., 57., 15., 83.],
       [95., 28., 41., 22., 87.],
       [49., 35., 91., 30., 24.],
       [29., 50., 88., 31., 11.],
       [19., 91., 98., 22., 87.]])

In [150]:
# How to find common values between two arrays?

a1 = np.random.randint(0, 100, (5, 5))
a2 = np.random.randint(0, 100, (5, 5))

intersection = np.intersect1d(a1, a2)
print(a1)
print(a2)
print(intersection)

[[42 22 62 15 45]
 [56 28 51 46  3]
 [35 60 33 40 38]
 [46 53 85 25  5]
 [24 26 54 39 53]]
[[70 71 23 87 61]
 [45 75 14 97 73]
 [56 20 42 44 62]
 [41 38 87 68 72]
 [ 9 68 87 47 72]]
[38 42 45 56 62]


In [ ]:
# How to ignore all numpy warnings (not recommended .d )

np.seterr(all='ignore')  # to go back, we have: np.seterr(**defaults)
# equivalently, with a context manager with: np.errstate(all="ignore"): np.arange(3) / 0

In [ ]:
# 32 Is the following expressions true?

np.sqrt(-1) == np.emath.sqrt(-1)
# np.False because first is np.nan and the second is 1j

In [ ]:
# 33 How to get the dates of yesterday, today and tomorrow

np.datetime64("today") 
np.datetime64("today") - 1 # or np.datetime64("today") - np.timedelta64(1, 'day')
np.datetime64("today") + 1

np.datetime64('2025-05-22')